#!/bin/bash
reconstructPar -latestTime

postProcess -func sample -latestTime

# 设置路径
base_path="/home/xsj/lk/1126-1203/SandiaD_LTS_1/postProcessing/sample"
python_file="/home/xsj/lk/1126-1203/SandiaD_LTS_1/plot.py"  # 修改为你的 Python 文件路径

# 获取最新的时刻（文件夹名）
latest_time=$(find "$base_path" -maxdepth 1 -type d | awk -F/ '{print $NF}' | grep -E '^[0-9]+\.[0-9]+$' | sort -n | tail -n 1)

# # 检查是否找到时刻
# if [ -z "$latest_time" ] ; then
#     echo "未找到有效的时间戳文件夹!"
#     exit 1
# fi

# echo "最新时刻: $latest_time"

# 使用 sed 修改 Python 文件中的时间戳

current_time_step=$(grep -oP '(?<=/)[0-9]+\.[0-9]+(?=/)' "$python_file" | head -n 1)

sed -i "s|/$current_time_step/|/$latest_time/|g" "$python_file"

# echo "Python 脚本中的路径已更新为最新时刻: $latest_time"

python plot.py
